### ISSUE TITLE
StackTop.push is not a function error

### ISSUE THREAD

**Issue by stajima** [hash-bang/bfj-collections#2]
Hello, while using bfjc I encountered a parsing error. It seems something about the structure of the object being parsed causes stackTop to break.
```
error TypeError: stackTop.push is not a function
    at EventEmitter.emitter.on (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bfj-collections/index.js:44:14)
    at EventEmitter.emit (events.js:198:13)
    at then (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bfj/src/walk.js:327:19)
    at tryCatcher (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tajimas/Dev/lexivore-ingestor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
```
[
  {
    "occupation": [[], [{}]]
  }
]
```
Returned object after breakage: `{ occupation: [] }`

**Comment by hash-bang** [comment]
Thanks for the feedback.
Fixed in `1.0.5`
